name: Build and Release FastXT

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore FastXT/FastXT.csproj

    - name: Build
      run: dotnet build FastXT/FastXT.csproj --configuration Release --no-restore

    - name: Publish for Windows x64
      run: dotnet publish FastXT/FastXT.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: FastXT-win-x64
        path: ./publish/FastXT.exe

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish for Windows x64
      run: dotnet publish FastXT/FastXT.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:PublishReadyToRun=true -o ./publish

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/FastXT.exe
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
